// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/dlt.proto

package trading.rpc;

public final class DLTOutter {
  private DLTOutter() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TxnRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:jraft.TxnRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string txnHash = 1;</code>
     * @return Whether the txnHash field is set.
     */
    boolean hasTxnHash();
    /**
     * <code>required string txnHash = 1;</code>
     * @return The txnHash.
     */
    java.lang.String getTxnHash();
    /**
     * <code>required string txnHash = 1;</code>
     * @return The bytes for txnHash.
     */
    com.google.protobuf.ByteString
        getTxnHashBytes();
  }
  /**
   * Protobuf type {@code jraft.TxnRequest}
   */
  public static final class TxnRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:jraft.TxnRequest)
      TxnRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TxnRequest.newBuilder() to construct.
    private TxnRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TxnRequest() {
      txnHash_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TxnRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TxnRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              txnHash_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return trading.rpc.DLTOutter.internal_static_jraft_TxnRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return trading.rpc.DLTOutter.internal_static_jraft_TxnRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              trading.rpc.DLTOutter.TxnRequest.class, trading.rpc.DLTOutter.TxnRequest.Builder.class);
    }

    private int bitField0_;
    public static final int TXNHASH_FIELD_NUMBER = 1;
    private volatile java.lang.Object txnHash_;
    /**
     * <code>required string txnHash = 1;</code>
     * @return Whether the txnHash field is set.
     */
    @java.lang.Override
    public boolean hasTxnHash() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string txnHash = 1;</code>
     * @return The txnHash.
     */
    @java.lang.Override
    public java.lang.String getTxnHash() {
      java.lang.Object ref = txnHash_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          txnHash_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string txnHash = 1;</code>
     * @return The bytes for txnHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTxnHashBytes() {
      java.lang.Object ref = txnHash_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        txnHash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTxnHash()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, txnHash_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, txnHash_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof trading.rpc.DLTOutter.TxnRequest)) {
        return super.equals(obj);
      }
      trading.rpc.DLTOutter.TxnRequest other = (trading.rpc.DLTOutter.TxnRequest) obj;

      if (hasTxnHash() != other.hasTxnHash()) return false;
      if (hasTxnHash()) {
        if (!getTxnHash()
            .equals(other.getTxnHash())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTxnHash()) {
        hash = (37 * hash) + TXNHASH_FIELD_NUMBER;
        hash = (53 * hash) + getTxnHash().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static trading.rpc.DLTOutter.TxnRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static trading.rpc.DLTOutter.TxnRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static trading.rpc.DLTOutter.TxnRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static trading.rpc.DLTOutter.TxnRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static trading.rpc.DLTOutter.TxnRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static trading.rpc.DLTOutter.TxnRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static trading.rpc.DLTOutter.TxnRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static trading.rpc.DLTOutter.TxnRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static trading.rpc.DLTOutter.TxnRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static trading.rpc.DLTOutter.TxnRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static trading.rpc.DLTOutter.TxnRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static trading.rpc.DLTOutter.TxnRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(trading.rpc.DLTOutter.TxnRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code jraft.TxnRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:jraft.TxnRequest)
        trading.rpc.DLTOutter.TxnRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return trading.rpc.DLTOutter.internal_static_jraft_TxnRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return trading.rpc.DLTOutter.internal_static_jraft_TxnRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                trading.rpc.DLTOutter.TxnRequest.class, trading.rpc.DLTOutter.TxnRequest.Builder.class);
      }

      // Construct using trading.rpc.DLTOutter.TxnRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        txnHash_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return trading.rpc.DLTOutter.internal_static_jraft_TxnRequest_descriptor;
      }

      @java.lang.Override
      public trading.rpc.DLTOutter.TxnRequest getDefaultInstanceForType() {
        return trading.rpc.DLTOutter.TxnRequest.getDefaultInstance();
      }

      @java.lang.Override
      public trading.rpc.DLTOutter.TxnRequest build() {
        trading.rpc.DLTOutter.TxnRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public trading.rpc.DLTOutter.TxnRequest buildPartial() {
        trading.rpc.DLTOutter.TxnRequest result = new trading.rpc.DLTOutter.TxnRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.txnHash_ = txnHash_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof trading.rpc.DLTOutter.TxnRequest) {
          return mergeFrom((trading.rpc.DLTOutter.TxnRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(trading.rpc.DLTOutter.TxnRequest other) {
        if (other == trading.rpc.DLTOutter.TxnRequest.getDefaultInstance()) return this;
        if (other.hasTxnHash()) {
          bitField0_ |= 0x00000001;
          txnHash_ = other.txnHash_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasTxnHash()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        trading.rpc.DLTOutter.TxnRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (trading.rpc.DLTOutter.TxnRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object txnHash_ = "";
      /**
       * <code>required string txnHash = 1;</code>
       * @return Whether the txnHash field is set.
       */
      public boolean hasTxnHash() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string txnHash = 1;</code>
       * @return The txnHash.
       */
      public java.lang.String getTxnHash() {
        java.lang.Object ref = txnHash_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            txnHash_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string txnHash = 1;</code>
       * @return The bytes for txnHash.
       */
      public com.google.protobuf.ByteString
          getTxnHashBytes() {
        java.lang.Object ref = txnHash_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          txnHash_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string txnHash = 1;</code>
       * @param value The txnHash to set.
       * @return This builder for chaining.
       */
      public Builder setTxnHash(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        txnHash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string txnHash = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTxnHash() {
        bitField0_ = (bitField0_ & ~0x00000001);
        txnHash_ = getDefaultInstance().getTxnHash();
        onChanged();
        return this;
      }
      /**
       * <code>required string txnHash = 1;</code>
       * @param value The bytes for txnHash to set.
       * @return This builder for chaining.
       */
      public Builder setTxnHashBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        txnHash_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:jraft.TxnRequest)
    }

    // @@protoc_insertion_point(class_scope:jraft.TxnRequest)
    private static final trading.rpc.DLTOutter.TxnRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new trading.rpc.DLTOutter.TxnRequest();
    }

    public static trading.rpc.DLTOutter.TxnRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<TxnRequest>
        PARSER = new com.google.protobuf.AbstractParser<TxnRequest>() {
      @java.lang.Override
      public TxnRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TxnRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TxnRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TxnRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public trading.rpc.DLTOutter.TxnRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TxnResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:jraft.TxnResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string txnHash = 1;</code>
     * @return Whether the txnHash field is set.
     */
    boolean hasTxnHash();
    /**
     * <code>required string txnHash = 1;</code>
     * @return The txnHash.
     */
    java.lang.String getTxnHash();
    /**
     * <code>required string txnHash = 1;</code>
     * @return The bytes for txnHash.
     */
    com.google.protobuf.ByteString
        getTxnHashBytes();

    /**
     * <pre>
     * return the transaction order to the request sender
     * </pre>
     *
     * <code>required int32 txnOrder = 2;</code>
     * @return Whether the txnOrder field is set.
     */
    boolean hasTxnOrder();
    /**
     * <pre>
     * return the transaction order to the request sender
     * </pre>
     *
     * <code>required int32 txnOrder = 2;</code>
     * @return The txnOrder.
     */
    int getTxnOrder();

    /**
     * <code>required bool success = 3;</code>
     * @return Whether the success field is set.
     */
    boolean hasSuccess();
    /**
     * <code>required bool success = 3;</code>
     * @return The success.
     */
    boolean getSuccess();

    /**
     * <code>optional string redirect = 4;</code>
     * @return Whether the redirect field is set.
     */
    boolean hasRedirect();
    /**
     * <code>optional string redirect = 4;</code>
     * @return The redirect.
     */
    java.lang.String getRedirect();
    /**
     * <code>optional string redirect = 4;</code>
     * @return The bytes for redirect.
     */
    com.google.protobuf.ByteString
        getRedirectBytes();

    /**
     * <code>optional string errorMsg = 5;</code>
     * @return Whether the errorMsg field is set.
     */
    boolean hasErrorMsg();
    /**
     * <code>optional string errorMsg = 5;</code>
     * @return The errorMsg.
     */
    java.lang.String getErrorMsg();
    /**
     * <code>optional string errorMsg = 5;</code>
     * @return The bytes for errorMsg.
     */
    com.google.protobuf.ByteString
        getErrorMsgBytes();
  }
  /**
   * Protobuf type {@code jraft.TxnResponse}
   */
  public static final class TxnResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:jraft.TxnResponse)
      TxnResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TxnResponse.newBuilder() to construct.
    private TxnResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TxnResponse() {
      txnHash_ = "";
      redirect_ = "";
      errorMsg_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TxnResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TxnResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              txnHash_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              txnOrder_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              success_ = input.readBool();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              redirect_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              errorMsg_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return trading.rpc.DLTOutter.internal_static_jraft_TxnResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return trading.rpc.DLTOutter.internal_static_jraft_TxnResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              trading.rpc.DLTOutter.TxnResponse.class, trading.rpc.DLTOutter.TxnResponse.Builder.class);
    }

    private int bitField0_;
    public static final int TXNHASH_FIELD_NUMBER = 1;
    private volatile java.lang.Object txnHash_;
    /**
     * <code>required string txnHash = 1;</code>
     * @return Whether the txnHash field is set.
     */
    @java.lang.Override
    public boolean hasTxnHash() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string txnHash = 1;</code>
     * @return The txnHash.
     */
    @java.lang.Override
    public java.lang.String getTxnHash() {
      java.lang.Object ref = txnHash_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          txnHash_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string txnHash = 1;</code>
     * @return The bytes for txnHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTxnHashBytes() {
      java.lang.Object ref = txnHash_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        txnHash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TXNORDER_FIELD_NUMBER = 2;
    private int txnOrder_;
    /**
     * <pre>
     * return the transaction order to the request sender
     * </pre>
     *
     * <code>required int32 txnOrder = 2;</code>
     * @return Whether the txnOrder field is set.
     */
    @java.lang.Override
    public boolean hasTxnOrder() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * return the transaction order to the request sender
     * </pre>
     *
     * <code>required int32 txnOrder = 2;</code>
     * @return The txnOrder.
     */
    @java.lang.Override
    public int getTxnOrder() {
      return txnOrder_;
    }

    public static final int SUCCESS_FIELD_NUMBER = 3;
    private boolean success_;
    /**
     * <code>required bool success = 3;</code>
     * @return Whether the success field is set.
     */
    @java.lang.Override
    public boolean hasSuccess() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required bool success = 3;</code>
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return success_;
    }

    public static final int REDIRECT_FIELD_NUMBER = 4;
    private volatile java.lang.Object redirect_;
    /**
     * <code>optional string redirect = 4;</code>
     * @return Whether the redirect field is set.
     */
    @java.lang.Override
    public boolean hasRedirect() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string redirect = 4;</code>
     * @return The redirect.
     */
    @java.lang.Override
    public java.lang.String getRedirect() {
      java.lang.Object ref = redirect_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          redirect_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string redirect = 4;</code>
     * @return The bytes for redirect.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRedirectBytes() {
      java.lang.Object ref = redirect_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        redirect_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ERRORMSG_FIELD_NUMBER = 5;
    private volatile java.lang.Object errorMsg_;
    /**
     * <code>optional string errorMsg = 5;</code>
     * @return Whether the errorMsg field is set.
     */
    @java.lang.Override
    public boolean hasErrorMsg() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string errorMsg = 5;</code>
     * @return The errorMsg.
     */
    @java.lang.Override
    public java.lang.String getErrorMsg() {
      java.lang.Object ref = errorMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errorMsg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string errorMsg = 5;</code>
     * @return The bytes for errorMsg.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getErrorMsgBytes() {
      java.lang.Object ref = errorMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTxnHash()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTxnOrder()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSuccess()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, txnHash_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, txnOrder_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeBool(3, success_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, redirect_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, errorMsg_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, txnHash_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, txnOrder_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, success_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, redirect_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, errorMsg_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof trading.rpc.DLTOutter.TxnResponse)) {
        return super.equals(obj);
      }
      trading.rpc.DLTOutter.TxnResponse other = (trading.rpc.DLTOutter.TxnResponse) obj;

      if (hasTxnHash() != other.hasTxnHash()) return false;
      if (hasTxnHash()) {
        if (!getTxnHash()
            .equals(other.getTxnHash())) return false;
      }
      if (hasTxnOrder() != other.hasTxnOrder()) return false;
      if (hasTxnOrder()) {
        if (getTxnOrder()
            != other.getTxnOrder()) return false;
      }
      if (hasSuccess() != other.hasSuccess()) return false;
      if (hasSuccess()) {
        if (getSuccess()
            != other.getSuccess()) return false;
      }
      if (hasRedirect() != other.hasRedirect()) return false;
      if (hasRedirect()) {
        if (!getRedirect()
            .equals(other.getRedirect())) return false;
      }
      if (hasErrorMsg() != other.hasErrorMsg()) return false;
      if (hasErrorMsg()) {
        if (!getErrorMsg()
            .equals(other.getErrorMsg())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTxnHash()) {
        hash = (37 * hash) + TXNHASH_FIELD_NUMBER;
        hash = (53 * hash) + getTxnHash().hashCode();
      }
      if (hasTxnOrder()) {
        hash = (37 * hash) + TXNORDER_FIELD_NUMBER;
        hash = (53 * hash) + getTxnOrder();
      }
      if (hasSuccess()) {
        hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getSuccess());
      }
      if (hasRedirect()) {
        hash = (37 * hash) + REDIRECT_FIELD_NUMBER;
        hash = (53 * hash) + getRedirect().hashCode();
      }
      if (hasErrorMsg()) {
        hash = (37 * hash) + ERRORMSG_FIELD_NUMBER;
        hash = (53 * hash) + getErrorMsg().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static trading.rpc.DLTOutter.TxnResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static trading.rpc.DLTOutter.TxnResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static trading.rpc.DLTOutter.TxnResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static trading.rpc.DLTOutter.TxnResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static trading.rpc.DLTOutter.TxnResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static trading.rpc.DLTOutter.TxnResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static trading.rpc.DLTOutter.TxnResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static trading.rpc.DLTOutter.TxnResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static trading.rpc.DLTOutter.TxnResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static trading.rpc.DLTOutter.TxnResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static trading.rpc.DLTOutter.TxnResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static trading.rpc.DLTOutter.TxnResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(trading.rpc.DLTOutter.TxnResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code jraft.TxnResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:jraft.TxnResponse)
        trading.rpc.DLTOutter.TxnResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return trading.rpc.DLTOutter.internal_static_jraft_TxnResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return trading.rpc.DLTOutter.internal_static_jraft_TxnResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                trading.rpc.DLTOutter.TxnResponse.class, trading.rpc.DLTOutter.TxnResponse.Builder.class);
      }

      // Construct using trading.rpc.DLTOutter.TxnResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        txnHash_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        txnOrder_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        success_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        redirect_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        errorMsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return trading.rpc.DLTOutter.internal_static_jraft_TxnResponse_descriptor;
      }

      @java.lang.Override
      public trading.rpc.DLTOutter.TxnResponse getDefaultInstanceForType() {
        return trading.rpc.DLTOutter.TxnResponse.getDefaultInstance();
      }

      @java.lang.Override
      public trading.rpc.DLTOutter.TxnResponse build() {
        trading.rpc.DLTOutter.TxnResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public trading.rpc.DLTOutter.TxnResponse buildPartial() {
        trading.rpc.DLTOutter.TxnResponse result = new trading.rpc.DLTOutter.TxnResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.txnHash_ = txnHash_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.txnOrder_ = txnOrder_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.success_ = success_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.redirect_ = redirect_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          to_bitField0_ |= 0x00000010;
        }
        result.errorMsg_ = errorMsg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof trading.rpc.DLTOutter.TxnResponse) {
          return mergeFrom((trading.rpc.DLTOutter.TxnResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(trading.rpc.DLTOutter.TxnResponse other) {
        if (other == trading.rpc.DLTOutter.TxnResponse.getDefaultInstance()) return this;
        if (other.hasTxnHash()) {
          bitField0_ |= 0x00000001;
          txnHash_ = other.txnHash_;
          onChanged();
        }
        if (other.hasTxnOrder()) {
          setTxnOrder(other.getTxnOrder());
        }
        if (other.hasSuccess()) {
          setSuccess(other.getSuccess());
        }
        if (other.hasRedirect()) {
          bitField0_ |= 0x00000008;
          redirect_ = other.redirect_;
          onChanged();
        }
        if (other.hasErrorMsg()) {
          bitField0_ |= 0x00000010;
          errorMsg_ = other.errorMsg_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasTxnHash()) {
          return false;
        }
        if (!hasTxnOrder()) {
          return false;
        }
        if (!hasSuccess()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        trading.rpc.DLTOutter.TxnResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (trading.rpc.DLTOutter.TxnResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object txnHash_ = "";
      /**
       * <code>required string txnHash = 1;</code>
       * @return Whether the txnHash field is set.
       */
      public boolean hasTxnHash() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string txnHash = 1;</code>
       * @return The txnHash.
       */
      public java.lang.String getTxnHash() {
        java.lang.Object ref = txnHash_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            txnHash_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string txnHash = 1;</code>
       * @return The bytes for txnHash.
       */
      public com.google.protobuf.ByteString
          getTxnHashBytes() {
        java.lang.Object ref = txnHash_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          txnHash_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string txnHash = 1;</code>
       * @param value The txnHash to set.
       * @return This builder for chaining.
       */
      public Builder setTxnHash(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        txnHash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string txnHash = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTxnHash() {
        bitField0_ = (bitField0_ & ~0x00000001);
        txnHash_ = getDefaultInstance().getTxnHash();
        onChanged();
        return this;
      }
      /**
       * <code>required string txnHash = 1;</code>
       * @param value The bytes for txnHash to set.
       * @return This builder for chaining.
       */
      public Builder setTxnHashBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        txnHash_ = value;
        onChanged();
        return this;
      }

      private int txnOrder_ ;
      /**
       * <pre>
       * return the transaction order to the request sender
       * </pre>
       *
       * <code>required int32 txnOrder = 2;</code>
       * @return Whether the txnOrder field is set.
       */
      @java.lang.Override
      public boolean hasTxnOrder() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * return the transaction order to the request sender
       * </pre>
       *
       * <code>required int32 txnOrder = 2;</code>
       * @return The txnOrder.
       */
      @java.lang.Override
      public int getTxnOrder() {
        return txnOrder_;
      }
      /**
       * <pre>
       * return the transaction order to the request sender
       * </pre>
       *
       * <code>required int32 txnOrder = 2;</code>
       * @param value The txnOrder to set.
       * @return This builder for chaining.
       */
      public Builder setTxnOrder(int value) {
        bitField0_ |= 0x00000002;
        txnOrder_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * return the transaction order to the request sender
       * </pre>
       *
       * <code>required int32 txnOrder = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTxnOrder() {
        bitField0_ = (bitField0_ & ~0x00000002);
        txnOrder_ = 0;
        onChanged();
        return this;
      }

      private boolean success_ ;
      /**
       * <code>required bool success = 3;</code>
       * @return Whether the success field is set.
       */
      @java.lang.Override
      public boolean hasSuccess() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required bool success = 3;</code>
       * @return The success.
       */
      @java.lang.Override
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>required bool success = 3;</code>
       * @param value The success to set.
       * @return This builder for chaining.
       */
      public Builder setSuccess(boolean value) {
        bitField0_ |= 0x00000004;
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool success = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSuccess() {
        bitField0_ = (bitField0_ & ~0x00000004);
        success_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object redirect_ = "";
      /**
       * <code>optional string redirect = 4;</code>
       * @return Whether the redirect field is set.
       */
      public boolean hasRedirect() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional string redirect = 4;</code>
       * @return The redirect.
       */
      public java.lang.String getRedirect() {
        java.lang.Object ref = redirect_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            redirect_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string redirect = 4;</code>
       * @return The bytes for redirect.
       */
      public com.google.protobuf.ByteString
          getRedirectBytes() {
        java.lang.Object ref = redirect_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          redirect_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string redirect = 4;</code>
       * @param value The redirect to set.
       * @return This builder for chaining.
       */
      public Builder setRedirect(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        redirect_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string redirect = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearRedirect() {
        bitField0_ = (bitField0_ & ~0x00000008);
        redirect_ = getDefaultInstance().getRedirect();
        onChanged();
        return this;
      }
      /**
       * <code>optional string redirect = 4;</code>
       * @param value The bytes for redirect to set.
       * @return This builder for chaining.
       */
      public Builder setRedirectBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        redirect_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object errorMsg_ = "";
      /**
       * <code>optional string errorMsg = 5;</code>
       * @return Whether the errorMsg field is set.
       */
      public boolean hasErrorMsg() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional string errorMsg = 5;</code>
       * @return The errorMsg.
       */
      public java.lang.String getErrorMsg() {
        java.lang.Object ref = errorMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            errorMsg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string errorMsg = 5;</code>
       * @return The bytes for errorMsg.
       */
      public com.google.protobuf.ByteString
          getErrorMsgBytes() {
        java.lang.Object ref = errorMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string errorMsg = 5;</code>
       * @param value The errorMsg to set.
       * @return This builder for chaining.
       */
      public Builder setErrorMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        errorMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string errorMsg = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearErrorMsg() {
        bitField0_ = (bitField0_ & ~0x00000010);
        errorMsg_ = getDefaultInstance().getErrorMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string errorMsg = 5;</code>
       * @param value The bytes for errorMsg to set.
       * @return This builder for chaining.
       */
      public Builder setErrorMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        errorMsg_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:jraft.TxnResponse)
    }

    // @@protoc_insertion_point(class_scope:jraft.TxnResponse)
    private static final trading.rpc.DLTOutter.TxnResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new trading.rpc.DLTOutter.TxnResponse();
    }

    public static trading.rpc.DLTOutter.TxnResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<TxnResponse>
        PARSER = new com.google.protobuf.AbstractParser<TxnResponse>() {
      @java.lang.Override
      public TxnResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TxnResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TxnResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TxnResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public trading.rpc.DLTOutter.TxnResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jraft_TxnRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jraft_TxnRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jraft_TxnResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jraft_TxnResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034src/main/resources/dlt.proto\022\005jraft\"\035\n" +
      "\nTxnRequest\022\017\n\007txnHash\030\001 \002(\t\"e\n\013TxnRespo" +
      "nse\022\017\n\007txnHash\030\001 \002(\t\022\020\n\010txnOrder\030\002 \002(\005\022\017" +
      "\n\007success\030\003 \002(\010\022\020\n\010redirect\030\004 \001(\t\022\020\n\010err" +
      "orMsg\030\005 \001(\tB\030\n\013trading.rpcB\tDLTOutter"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_jraft_TxnRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_jraft_TxnRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jraft_TxnRequest_descriptor,
        new java.lang.String[] { "TxnHash", });
    internal_static_jraft_TxnResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_jraft_TxnResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jraft_TxnResponse_descriptor,
        new java.lang.String[] { "TxnHash", "TxnOrder", "Success", "Redirect", "ErrorMsg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
